### ISSUE TITLE
Thymeleaf : Thymeleaf Error

### ISSUE THREAD

**Issue by accidentlywoo** [cats-dance/book-shelf#15]
Thymeleaf dependency를 추가하고 template 설정을 했으나,

parsing error를 보이며, template engine이 제대로 동작하고 있지 않음.!!!

**Comment by accidentlywoo** [comment]
Error 부분 : 
> index.html
<div th:block th:replace="fragments/bodyHeader :: bodyHeader"/>
>header.html
<head th:fargment="header"> ~~

replace되는 html 태그가 일치해야지 템플릿 파싱이 동작한다!
Solve : 
> index.html
<**head** th:block th:replace="fragments/bodyHeader :: bodyHeader"/>
>header.html
<head th:fargment="header"> ~~

**Comment by jiphael** [comment]
왜 block 문법은 되고 block없이는 안될까유??

**Comment by accidentlywoo** [comment]
버전문제일 수도있고, 뻘짓을 많이했네요 하하하하하하 최신을 쓰면 쓸수록 이런문제가 많다는게 함정 😂
