### ISSUE TITLE
Repository Test Case 설계!

### ISSUE THREAD

**Issue by accidentlywoo** [cats-dance/book-shelf#9]
초기 Entity 설계가 마무리됬씀다!

Repository에 기본적인 Test Case를 작성해 두었는데, 추가 테스트 케이스가 필요한지 검토 해줏떄요잉

**Comment by jiphael** [comment]
와웅 수고하셨습니다아 회원정보수정(비밀번호,주소같은거), 책정보수정, 상품정보수정, 상품등록 테스트도 필요할꺼 같아요???!
